services:
  - type: web
    name: movie-time
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: '3000'
      - key: DATABASE_URL
        sync: false
      - key: OMDB_API_KEY
        sync: false
    plan: free
    deployment:
      minInstances: 1
      maxInstances: 3
